version: "3.7"

volumes:
  mysql-data: {}

services:
  nginx:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    volumes:
      - ./app:/var/www/html/app
    ports:
      - "${HTTP_PORT}:80"

  php-fpm:
    build:
      context: ./
      dockerfile: php-fpm/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=docker
    volumes:
      - ./app:/var/www/html/app

  mysql:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}

  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:6379"

  adminer:
    image: adminer
    ports:
      - "8095:8080"
